In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
import numpy as np
import random
data=[1,23,44,5]
print(type(data))

<class 'list'>


In [15]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.split(a,2),np.split(a,5)

([array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])],
 [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])])

In [17]:
## array_split divides the aarray unequally
np.array_split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [18]:
## dsplit split the array into 3 dimentional array
np.dsplit(a,3)

ValueError: dsplit only works on arrays of 3 or more dimensions

In [19]:
# lets create a numpy array
arr = np.array(data)
arr

array([ 1, 23, 44,  5])

In [20]:
print(arr.ndim)

1


In [21]:
# we can create a 2D array
# nested list( [[1,2,3],[5,4,7],[4,3,2]])
a= [[1,2,3],[5,4,7],[4,3,2]]
arr2 = np.array(a)
arr2

array([[1, 2, 3],
       [5, 4, 7],
       [4, 3, 2]])

In [22]:
arr2.shape

(3, 3)

In [23]:
## trace of matrix
arr2.trace() # trace do sum of midle diagonal(i.e.., in X form)

7

In [24]:
## transpose of array
arr2.T

array([[1, 5, 4],
       [2, 4, 3],
       [3, 7, 2]])

In [25]:
### slicing
##### data[row,col]
#### data[start:stop:step,start:stop:step]

In [18]:
arr2[0:2,1:]


array([[2, 3],
       [4, 7]])

In [19]:
arr2[1:2,1:]

array([[4, 7]])

In [20]:
arr2[1::+1,0:2+1]

array([[5, 4, 7],
       [4, 3, 2]])

In [21]:
## age of student
arr =np.array([12,36,87,45,342,90])
arr

array([ 12,  36,  87,  45, 342,  90])

In [22]:
#max function
arr.max()

342

In [23]:
# min function
arr.min()

12

In [24]:
# mean function
arr.mean()

102.0

In [25]:
# standard deviation i.e, std function
arr.std()

110.81064930772673

In [26]:
## stacking in array
# vstack(),hstack()
## for the dimension should be the same

In [27]:
arr1 = np.array ([[1,2],[3,5]])
arr2 = np.array ([[11,12],[22,33]])

In [28]:
final = np.vstack((arr1,arr2))
final

array([[ 1,  2],
       [ 3,  5],
       [11, 12],
       [22, 33]])

In [29]:
final = np.hstack((arr1,arr2))
final

array([[ 1,  2, 11, 12],
       [ 3,  5, 22, 33]])

In [30]:
# zeros / ones array
print(np.ones([5,1]))

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [31]:
print(np.ones([5,1],dtype = np.int64)*5)

[[5]
 [5]
 [5]
 [5]
 [5]]


In [32]:
## zeros 
np.zeros[4,5]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [33]:
print(dir(arr))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [34]:
## flatten convert into 1D array
arr1 = np.array([[1,2],[34,56]])
arr1

array([[ 1,  2],
       [34, 56]])

In [35]:
v=arr1.flatten()

In [36]:
v

array([ 1,  2, 34, 56])

In [37]:
v.ndim

1

#### pandas : panel data analysis
#### pandas has three 
* Series :1D structure
* DataFrame:2D structure
* Panel data :3D 


In [38]:
## np.random.seed(1) seed for reproducibility
x=np.random.randint(10,size=6)# 1D
x             

array([9, 7, 5, 4, 1, 7])

In [39]:
xx=np.random.randint(10, size=(3,3)) # 2D
xx

array([[0, 0, 1],
       [5, 3, 2],
       [5, 1, 3]])

In [40]:

xxx=np.random.randint(10,size=(3,4,5))   #3D  
xxx

array([[[6, 5, 6, 9, 8],
        [2, 6, 9, 3, 9],
        [1, 7, 7, 8, 9],
        [4, 1, 0, 0, 2]],

       [[2, 1, 5, 2, 5],
        [9, 3, 6, 6, 0],
        [6, 4, 6, 2, 0],
        [3, 3, 3, 5, 3]],

       [[2, 5, 5, 6, 1],
        [8, 2, 8, 3, 7],
        [1, 7, 0, 1, 0],
        [9, 7, 9, 8, 1]]])

In [41]:
print("itemsize:",x.itemsize,"bytes")

itemsize: 4 bytes


In [42]:
xx[0,0]=15 ## replacing value
xx

array([[15,  0,  1],
       [ 5,  3,  2],
       [ 5,  1,  3]])

In [43]:
xx[1,2]=12
xx

array([[15,  0,  1],
       [ 5,  3, 12],
       [ 5,  1,  3]])

In [44]:
xxx[0,2,3] # element no,row,column
xxx

array([[[6, 5, 6, 9, 8],
        [2, 6, 9, 3, 9],
        [1, 7, 7, 8, 9],
        [4, 1, 0, 0, 2]],

       [[2, 1, 5, 2, 5],
        [9, 3, 6, 6, 0],
        [6, 4, 6, 2, 0],
        [3, 3, 3, 5, 3]],

       [[2, 5, 5, 6, 1],
        [8, 2, 8, 3, 7],
        [1, 7, 0, 1, 0],
        [9, 7, 9, 8, 1]]])

In [45]:
x1=np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### slicing

In [46]:
x1[:5]

array([0, 1, 2, 3, 4])

In [47]:
x1[1::2] # every other ele starting at index 1,skiping 1 ele

array([1, 3, 5, 7, 9])

In [48]:
## reversed
x1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
x1[5::-1]  ## reversing up to 5

array([5, 4, 3, 2, 1, 0])

In [50]:
xx

array([[15,  0,  1],
       [ 5,  3, 12],
       [ 5,  1,  3]])

In [51]:
xx[1:,0::2]

array([[ 5, 12],
       [ 5,  3]])

In [52]:
xx[0:2,1:]

array([[ 0,  1],
       [ 3, 12]])

In [53]:
xx[:1]

array([[15,  0,  1]])

In [54]:
xx[0:2,0:2] ## 2 rows 2 columns

array([[15,  0],
       [ 5,  3]])

In [55]:
xx[::-1,::-1] ## all rows and all col in reverse order

array([[ 3,  1,  5],
       [12,  3,  5],
       [ 1,  0, 15]])

In [56]:
xxx

array([[[6, 5, 6, 9, 8],
        [2, 6, 9, 3, 9],
        [1, 7, 7, 8, 9],
        [4, 1, 0, 0, 2]],

       [[2, 1, 5, 2, 5],
        [9, 3, 6, 6, 0],
        [6, 4, 6, 2, 0],
        [3, 3, 3, 5, 3]],

       [[2, 5, 5, 6, 1],
        [8, 2, 8, 3, 7],
        [1, 7, 0, 1, 0],
        [9, 7, 9, 8, 1]]])

In [57]:
xxx[1,:2,0::2] 

array([[2, 5, 5],
       [9, 6, 0]])

In [58]:
for i in range(2):
    print(xxx[1,0:2,0::2])

[[2 5 5]
 [9 6 0]]
[[2 5 5]
 [9 6 0]]


### Reshaping of arrays


In [59]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
grid = np.arange(1,10).reshape((3,3) )## converting 1D arr to 2D arr
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
x=np.array([1,2,3])
# row vector via reshape
x.reshape


<function ndarray.reshape>

In [62]:
x[:,np.newaxis] ## reshaping on column

array([[1],
       [2],
       [3]])

### Concatenation of arrays


In [63]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [64]:
## more thn 2 arrays at a time
z=np.array([6,6,8])
np.concatenate([x,y,z])

array([1, 2, 3, 3, 2, 1, 6, 6, 8])

In [65]:
grid=np.array([[1,2,3],[4,5,6]])

In [66]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

np.concatenate([grid,grid],axis=1)

grid=np.arange(16).reshape(4,4)
grid

In [67]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[1 2 3]
 [4 5 6]]
[]


#### Pandas :Pandas is an open source Python package that is most widely used for data science/data analysis and machine learning tasks. It is built on top of another package named Numpy, which provides support for multi-dimensional arrays.

### Features 
* Handling of data. The Pandas library provides a really fast and efficient way to manage and explore data. ...
* Alignment and indexing. ...
* Handling missing data. ...
* Cleaning up data. ...
* Input and output tools. ...
* Multiple file formats supported. ...
* Merging and joining of datasets. ...
* A lot of time series.

In [68]:
### series is a 1d array

### Creating series from ndarray

In [69]:
import pandas as pd
a=list('12345678')
a

['1', '2', '3', '4', '5', '6', '7', '8']

In [70]:
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[100,101,102,103])
print (s)

100    a
101    b
102    c
103    d
dtype: object


In [71]:
data = {'a' : 0, 'b' : 1, 'c' : 2}
s = pd.Series(data)
print (s)

a    0
b    1
c    2
dtype: int64


In [72]:
data1 = {'a' : 0.0, 'b' : 1.0, 'c' : 2.0}
s1 = pd.Series(data1,index=['b','c','d','a'])
print (s1)

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


In [73]:
s = pd.Series(5, index=[0, 1, 2, 3])
print (s)

0    5
1    5
2    5
3    5
dtype: int64


In [74]:
s.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [75]:
s.values

array([5, 5, 5, 5], dtype=int64)

In [76]:
s = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])

In [77]:
s = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [78]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [79]:
s['c']

3

In [80]:
s[['a','c','d']]

a    1
c    3
d    4
dtype: int64

In [81]:
data = [1,2,3,4,5]
df = pd.DataFrame(data)
df

0
0  1
1  2
2  3
3  4
4  5

In [82]:
 
data = [['Ramesh',10],['Himesh',12],['Kamesh',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
df

Name  Age
0  Ramesh   10
1  Himesh   12
2  Kamesh   13

In [83]:
data = [['Ramesh',10],['Himesh',12],['Kamesh',13]]
df = pd.DataFrame(data,columns=['Name','Age'], dtype=float)
df

Name   Age
0  Ramesh  10.0
1  Himesh  12.0
2  Kamesh  13.0

In [84]:
data = {'Name':['Nitesh','Ramesh','Rajesh','Nilesh'], 'Age':[28,34,29,45]}
df = pd.DataFrame(data)
df

Name  Age
0  Nitesh   28
1  Ramesh   34
2  Rajesh   29
3  Nilesh   45

### column selection ,addition,deletion

In [85]:
 df['Name']

0    Nitesh
1    Ramesh
2    Rajesh
3    Nilesh
Name: Name, dtype: object

In [86]:
d=d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
      'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)

# Adding a new column to an existing DataFrame object with column label by passing new series

print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print (df)

print()
print ("Adding a new column in DataFrame:")
df['four']=df['one']+df['three']
print (df)

Adding a new column by passing as Series:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

Adding a new column in DataFrame:
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN


In [87]:
# print ("Deleting the 1st column using DEL function:")
# del df['one']
# print (df)

# using pop function
print ("Deleting another column using POP function:")
df.pop('two')
print (df)

Deleting another column using POP function:
   one  three  four
a  1.0   10.0  11.0
b  2.0   20.0  22.0
c  3.0   30.0  33.0
d  NaN    NaN   NaN


In [88]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
print(df)
print("\n Accessing row having label 'b':")
print (df.loc['b'])

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

 Accessing row having label 'b':
one    2.0
two    2.0
Name: b, dtype: float64


In [89]:
 print (df.loc['b':'d'])

   one  two
b  2.0    2
c  3.0    3
d  NaN    4


In [90]:
print(df.iloc[1]) ## iloc:integer location

one    2.0
two    2.0
Name: b, dtype: float64


In [91]:
print(df.iloc)

In [92]:
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [93]:
df[['one']+['two']]

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [94]:
import pandas as pd
data=pd.read_excel("C:\Users\jyaku\OneDrive\Desktop\pandas_data.xlsx",sheetname="data")   

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-94-b0030f13da97>, line 2)

### Operation on data

In [95]:
data.dtypes

AttributeError: 'dict' object has no attribute 'dtypes'

In [96]:
data.info

AttributeError: 'dict' object has no attribute 'info'

In [97]:
data["col name"] =data["col name"].astype(np.int64)## chnage datatype of col

KeyError: 'col name'

In [98]:
data["col name"].valuecounts## counts/checks all the unique elements

KeyError: 'col name'

In [99]:
## misssing value check
data.isnull().sum()

AttributeError: 'dict' object has no attribute 'isnull'

In [100]:
(data.isnull.sum()/len(data))*100

AttributeError: 'dict' object has no attribute 'isnull'

In [101]:
data["col name"].fillna(12,inplace=True) # fill missing value

KeyError: 'col name'

In [102]:
### rename col
data.rename(columns={"ID" : "Employee ID"},inplace=True)

AttributeError: 'dict' object has no attribute 'rename'

In [103]:
# ho3w top extract data from dataframe based on condition
# and :&(numeric 7 key on board)
# or :| (just abbove enter button)
# extract all record for female

In [104]:
female_data = data[(data["gender"]=="F")]

KeyError: 'gender'

In [105]:
## extract male data where company type is 1
male_data = data[(data["gender"]=="M") & (data["company type"]==1)]

KeyError: 'gender'

### If -else in dataFrame

In [106]:
import pandas as pd
data["company_info"]="" 

In [107]:
## adding values in columns based on another cols
data["company_info"] = np.where(data["comapny type"]==1,"MNC",np.where(data["company type"]==2,"Domestic","local"))

KeyError: 'comapny type'

In [108]:
old=pd.DataFrame({"ID":[1,2,3],"Name":["a","b","c"]})

In [109]:
new=pd.DataFrame({"ID":[3,4,5],"Name":["d","e","f"]})

In [110]:
## how to chk whetjer the new data do nit contain any recoird from past

In [111]:
old

ID Name
0   1    a
1   2    b
2   3    c

In [112]:
var = old[(old["ID"].isin(new["ID"]))]

In [113]:
var

ID Name
2   3    c

In [114]:
var = old[~(old["ID"].isin(new["ID"]))]
var

ID Name
0   1    a
1   2    b

In [115]:
dup=pd.concat([old,new],axis=0)
dup

ID Name
0   1    a
1   2    b
2   3    c
0   3    d
1   4    e
2   5    f

In [116]:
dup=dup.drop_duplicates().reset_index()
dup

index  ID Name
0      0   1    a
1      1   2    b
2      2   3    c
3      0   3    d
4      1   4    e
5      2   5    f

In [117]:
## del extra column
dup=dup.drop(["index"],axis=1 )## axis 1 represent col
dup

ID Name
0   1    a
1   2    b
2   3    c
3   3    d
4   4    e
5   5    f

In [118]:
## you have to cancat this uncommon data to ew data to form records
final_data=pd.concat([var,new],axis=1)
final_data=


SyntaxError: invalid syntax (<ipython-input-118-b18a2e01b701>, line 3)

In [119]:
### how to check duplicates in dataframe(HM)

##join in python
* innere
* outer
* left
* right

In [120]:
## left_join 
data_left=pd.merge(j1,j2,left_on"Id",how="left")

SyntaxError: invalid syntax (<ipython-input-120-989bc0b9e0c3>, line 2)

In [121]:
data.to_excel("location_data",sheet name="data")

SyntaxError: invalid syntax (<ipython-input-121-e9002a97d768>, line 1)

In [122]:
## outer : contains all data
data_full=pd.merge(j1,j2,on"Id",how="outer")

SyntaxError: invalid syntax (<ipython-input-122-72ee4c225da9>, line 2)

In [123]:
## when the col namne is diff for both
 
data_left=pd.merge(j1,j2,left_on"Customer_Id",right_on="User_ID",how="left")

SyntaxError: invalid syntax (<ipython-input-123-dc3437cb4bba>, line 3)

In [124]:
### Pandas in dataFrame
pd.read_excel("C:\Users\Ricky\Desktop")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-124-13ccb50f1499>, line 2)